### ISSUE TITLE
CreateResendOrderAsync Content Type Error

### ISSUE THREAD

**Issue by AggieEngineer2k** [tangocard/raas-v2-sdk-dotnet-standard#5]
(v2.2.0 & v2.3.0)
TangoCard.Raas.RassClient.Orders.CreateResendOrderAsync() throws the following exception. The [API documentation](https://integration-www.tangocard.com/raas_api_console/v2/) seems to indicate only 'application/json' content type is supported.

API Error
---
HttpCode: 415
HttpPhrase: Unsupported Media Type
Message: Content type 'text/plain;charset=utf-8' not supported
Path: /raas/v2/orders/RA.../resends

**Comment by Thwar** [comment]
Having the same issue, I also tried the raas-v2-sdk-dotnet-pcl NuGet Package.

**Comment by AggieEngineer2k** [comment]
The last update I got from my account manager at TangoCard on 12/6/2018 was that their engineers are working on a resolution with APImatic and the SDK provider.  Will post an update when I hear back.

**Comment by AggieEngineer2k** [comment]
Master was updated to 2.3.3 which seems to have fixed the problem.
